### PR TITLE
Action list

### PR DESCRIPTION
**Pull request by richardolsson**
This PR implements the actions list from an early prototype, with draggable participants. It also adds an EditActionPane and the necessary flux actions and store logic to make it work.

### CODE REVIEW

**Comment by richardolsson** [comment]
This PR now implements these features:

* An action list with basic action information
* A pane to edit actions, reachable by clicking the "edit" link on an action in the list
* Crude participants list in each action item
* Dragging and dropping participants to stage moves between actions (without actually submitting them to the API)
* A participant move pane (see screenshot) which intelligently displays staged moves and shows up automatically when there are any logged moves
* A rollback feature to undo all moves
* A execute feature to submit the moves to the API

image


The move pane is a really nice feature for organizers, who often need to re-organize tomorrow's actions to evenly distribute participants. Being able to quickly move people around means you can get a nice composition of people by trial and error. 

Once the organizer is happy, the intelligent log (which rearranges to always display the shortest move) is a reference of what has been done and serves as a concise list of which activists need to be contacted to make sure they are fine with being moved. Once all are contacted, the moves can be executed and saved to the server.

**Comment by richardolsson** [comment]
Please take a look at this huge PR if you get a chance, @Bagera. I might merge it myself later if it turns out to be holding me up.

**Comment by Bagera** [comment]
This looks great. Great idea with the move list. Would it be useful to have a function to flag 2 ppl for move to the same spot and if you get acceptance from one of them it discards the move for the other person?
I'm ready to merge this but I have not done a code review.

**Comment by richardolsson** [comment]
Cool. With 1300 new LOC I don't blame you for not reviewing it all. :)

I will try to keep pull requests smaller in the future.

**Pull request merged**
