### PR TITLE
Importer improvements

### PR DESCRIPTION
**Pull request by richardolsson**
This PR improves the importer interface as described in #517.

screen shot 2017-03-16 at 17 10 54

### CODE REVIEW

**Comment by richardolsson** [comment]
Fixes #515 

However, we should still add some sort of indication of progress during parsing. Right now the browser just freezes during parsing. I will look into this.

**Comment by jensborje** [comment]
Styled up to the point of what we discussed. Please have a look @richardolsson (seems like I can't request review to other assignees).

**Comment by richardolsson** [comment]
Great work! Could you maybe add a cancel/abort button as well? If you want, I can hook it up to the right action tomorrow if you create and style a no-op button.

**Comment by jensborje** [comment]
screen shot 2017-03-17 at 11 59 54

**Comment by richardolsson** [comment]
Padding is off in the import summary.

image

**Comment by jensborje** [comment]
screen shot 2017-03-17 at 14 52 13

**Pull request merged**
