### PR TITLE
Action calendar styling 

### PR DESCRIPTION
**Pull request by hannis**
I've made some changes in the Action Calendar styling. It had turned the other way round due to new media queries (small screens had the desktop styling and vice versa). I hope and think it looks as it should now, but please take a closer look. 

actions_calendar

### CODE REVIEW

**Comment by hannis** [comment]
@richardolsson Glad to hear that it seems to look fine. About the panes, I will dive in to all that the next thing I do.

**Comment by hannis** [comment]
@richardolsson Sorry, I think I misunderstood you. Did you mean that the panes are not working as they should in general on desktop or is there a specific problem with them on the Action calendar?

**Comment by richardolsson** [comment]
I believe there are issues with panes in general, their positioning and z-index, on desktop on this branch. I assumed it was because you have made major CSS refactors and not gotten around to fixing the panes again. Do you consider this to be blocking a merge, or should I merge and you can take a look at pane issues at a later time?

**Comment by hannis** [comment]
@richardolsson I think you can go ahead and merge it now (I just added a small z-index change for the PaneBase class in my lastest commit a couple of minutes ago). I will dive in to the world of Panes from now on. It will probably take me a little while. I have to compare with the master branch and try to get them working as they used to. And then I also have to make them work on smaller screens. I will probably need some help with some JS-related Panes-stuff later I think.

**Pull request merged**
