### PR TITLE
Custom Fields in PersonForm

### LINKED ISSUE #1122: Edit custom field values
Add UI to edit custom field values.

One suggestion is to just add the field as regular fields in the `PersonForm`, but handle them differently when submitted.

### PR DESCRIPTION
**Pull request by richardolsson**
This PR adds custom fields to `PersonForm` in both `AddPersonPane` and `EditPersonPane`. This means that values for custom fields can now be set/reset the same way that values for "native" person fields.

Closes #1122

### CODE REVIEW

**Review by niklasva82 — APPROVED** [review]
Looks good! One issue is the lack of validation of URLs. PersonField doesn't do client-side validation at this point though so that's something for the future.

**Comment by richardolsson** [comment]
> Looks good! One issue is the lack of validation of URLs. PersonField doesn't do client-side validation at this point though so that's something for the future.

Thanks! I'm not sure what you were referring to here regarding client-side validation. Is this something that we should create a separate issue for?

**Comment by niklasva82** [comment]
There is one, albeit quite old. #43 
Wasn't this an issue at the last code camp? Or was it something related perhaps?

**Comment by richardolsson** [comment]
Ah, of course! I understand now. I was confused by the sheer amount of pull requests and lost track of the context. The form validation is one aspect. It was started at a code camp, but to be honest I don't think we should prioritize it because I believe we can do better with a proper UI framework in a future revamp (#1140).

This particular case could easily be covered by using an `<input type="url">` though, so maybe add an issue for creating a `<URLInput>` component?

**Pull request merged**
