### PR TITLE
Allow admins to set surveys as force_anonymous

### PR DESCRIPTION
**Pull request by niklasva82**

### CODE REVIEW

**Comment by richardolsson** [comment]
Is this ready to be reviewed?

**Comment by niklasva82** [comment]
> Is this ready to be reviewed?

Yes it is.

**Review by richardolsson — APPROVED** [review]
Clean and simple!

I think this is ready for merge, but I will hold off a little in case I manage to make a release later today or tomorrow morning.

**Comment by richardolsson** [comment]
I've created a local branch of master from before this, so I'll go ahead and merge anyway.

**Pull request merged**
