### PR TITLE
Refactor and use InfoList in more places

### PR DESCRIPTION
**Pull request by kesla**
Restructure how the `InfoList` Component work and use it in more places

### CODE REVIEW

**Comment by richardolsson** [comment]
We have rebased and force-pushed feature/canvass. Do you mind fast-forwarding your changes on top of the new feature/canvass and updating this PR?

**Comment by richardolsson** [comment]
Ping @kesla on the last comment. :)

**Comment by kesla** [comment]
@richardolsson Hey! Will get this done before EOD

**Comment by richardolsson** [comment]
@kesla: Did you find the time for this? Would love being able to avoid this huge merge. :)

**Comment by kesla** [comment]
@richardolsson Sorry for the delay, fixed

**Comment by richardolsson** [comment]
This is looking great! There are more places where this could be used. Do you want to implement `InfoList` in all other places before we merge, or should we go ahead and merge first and complete the refactor at some point down the line?

Other places that I can find are:
* `ActionPane` (From home, go to Campaign, scroll down in the calendar, click an action)
* `CallAssignmentPane` (From home, go to Dialog, click any of the two assignments)
* `SurveyPane` (From home, go to Survey, click any of the two surveys)

**Comment by kesla** [comment]
@richardolsson let's merge this now and I'll handle the reminder in a separate PR

**Comment by kesla** [comment]
@richardolsson I'm not a member of the zetkin organization so I can't merge my own PRs :)

**Pull request merged**
