### PR TITLE
Survey options view column

### PR DESCRIPTION
**Pull request by niklasva82**
This appears to work but is untested with multiple options and the styling is not great. It also concatenates all (unique) options from all submissions, I don't know if this is the best choice or not. Needs some further work.

### CODE REVIEW

**Comment by niklasva82** [comment]
Screenshot from 2022-11-12 02-39-01

**Comment by niklasva82** [comment]
Screenshot from 2022-11-16 16-52-16

**Comment by niklasva82** [comment]
Also sorted the selected options so that they are always in the same order, but maybe this is guaranteed anyways, I'm not sure?

**Review by richardolsson — APPROVED** [review]
LGTM! 💯

**Pull request merged**
